trigger: 
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: my-web-app

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'my-web-app'
    repository: 'my-web-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'